[package]
name = "dante-controller-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdns = "3.0.0"
futures-util = "0.3.28"
async-std = "1.12.0"
tokio = { version = "1.32.0", features = ["full"] }